apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-app
  template:
    metadata:
      labels:
        app: journal-app
    spec:
      containers:
        - name: journal-container
          image: dhanihaneesha/journal-app:v1
          ports:
            - containerPort: 5000
